name: build-neko

on:
  workflow_dispatch:



jobs:

  build-core:
    runs-on: windows-latest

    defaults:
      run:
        shell: pwsh
    
    steps:
    - name: 'Build Core'
      run: |
        $env:CHERE_INVOKING = 'yes'
        $env:MSYSTEM = 'CLANG64'
        $env:MSYS2_PATH_TYPE = 'inherit'
        git clone https://github.com/MatsuriDayo/nekoray.git --recursive
        cd nekoray
        C:\msys64\usr\bin\bash.exe -lc "./libs/get_source.sh"
        C:\msys64\usr\bin\bash.exe -lc "GOOS=windows GOARCH=amd64 bash libs/build_go.sh"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with: 
          name: nekobox-core
          path: '${{ github.workspace }}/nekoray/deployment/windows64/'


  build-ui:
    runs-on: windows-latest

    defaults:
      run:
        shell: cmd

    steps:
    - name: Checkout code
      uses: actions/checkout@v3   
    
    - name: Install Qt 6.7.3
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.7.3'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        set-env: 'true'
        add-tools-to-path: 'true'
 
    - name: build nekoray C++
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        choco install busybox
        git clone https://github.com/MatsuriDayo/nekoray.git --recursive
        cd nekoray
        busybox sh ./libs/build_deps_all.sh
        mkdir build
        cd build
        cmake -GNinja -DQT_VERSION_MAJOR=6 -DCMAKE_BUILD_TYPE=Release ..
        ninja
        mkdir deploy
        copy nekobox.exe deploy
        windeployqt deploy\nekobox.exe
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with: 
        name: nekobox
        path: '${{ github.workspace }}/nekoray/build/deploy/'

